baseURL = "https://somnus.top/"
languageCode = "zh"
title = "Somnus的小站"
enableEmoji = true

defaultContentLanguage = "zh"
hasCJKLanguage = true
removePathAccents = true
enableRobotsTXT = true
summaryLength = 30
timeout = 600000

[pagination]
pagerSize = 10

[build]
writeStats = true

[outputs]
home = ["HTML", "RSS", "headers", "redirects", "backlinks"]
section = ["HTML", "RSS"]

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"
publication_type = "publication_types"
