baseURL = "https://blog.somnus.top/"
languageCode = "zh-cn"
title = "Somnus的小站"
enableEmoji = true

defaultContentLanguage = "zh"
hasCJKLanguage = true
removePathAccents = true
enableRobotsTXT = true
summaryLength = 30
timeout = 600000
pluralizeListTitles = false
buildDrafts = false
buildFuture = false

[pagination]
pagerSize = 10

[build]
writeStats = true

[imaging]
anchor = "Center"

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS"]

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"
series = "series"
