[[imports]]
    path = "github.com/HugoBlox/kit/modules/integrations/netlify"

[[imports]]
    path = "github.com/HugoBlox/kit/modules/blox"

[[imports]]
    path = "github.com/HugoBlox/kit/modules/slides"
