colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true

enableA11y = false
enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true
replyByEmail = false

mainSections = ["posts"]
rssFullContent = true
fingerprintAlgorithm = "sha512"

[header]
layout = "fixed"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "profile"
showRecent = true
showRecentItems = 9
showMoreLink = true
showMoreLinkDest = "/posts/"
cardView = true
cardViewScreenWidth = false

[article]
showDate = true
showAuthor = true
showHero = false
showBreadcrumbs = true
showDraftLabel = true
showHeadingAnchors = true
showPagination = true
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showCategories = true
showTags = true
showWordCount = true
showZenMode = true

[list]
showHero = false
showBreadcrumbs = true
showSummary = true
showTableOfContents = false
showCards = false
groupByYear = true
cardView = false

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = true

[term]
showHero = false
showBreadcrumbs = true
showTableOfContents = false
groupByYear = true
cardView = false

[sitemap]
excludedKinds = ["taxonomy", "term"]
