#!/usr/bin/env node

import { readFile } from "node:fs/promises";
import { argv, exit } from "node:process";
import {
  decryptPayload,
  encryptText,
  getPassword,
  loadEnv,
  readJsonFile,
  writeJsonFile,
  writeTextFile
} from "./encryption-utils.mjs";

const GENERATED_NOTICE = "<!-- Generated by scripts/sync-private.mjs. Edit the matching .private source instead. -->";
const WORKFLOW_FRONT_MATTER_KEYS = [
  "encryptedTitle",
  "encryptedHint",
  "privateIndex",
  "privateIntro"
];

function usage() {
  console.error("Usage: node scripts/sync-private.mjs --encrypt [--manifest encrypted-manifest.json] [--index content/page/encrypted/index.md]");
  console.error("   or: node scripts/sync-private.mjs --decrypt [--manifest encrypted-manifest.json]");
  console.error("Set ENCRYPTION_PASSWORD in .env or your environment before running.");
}

function getArg(name) {
  const index = argv.indexOf(name);
  return index === -1 ? "" : argv[index + 1] || "";
}

function parseFrontMatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);

  if (!match) {
    return {
      frontMatter: "",
      body: content
    };
  }

  return {
    frontMatter: match[1].trim(),
    body: content.slice(match[0].length)
  };
}

function quoteYamlString(value) {
  return JSON.stringify(String(value));
}

function unquoteYamlString(value) {
  const trimmed = String(value || "").trim();

  if (
    (trimmed.startsWith('"') && trimmed.endsWith('"')) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    if (trimmed.startsWith('"')) {
      try {
        return JSON.parse(trimmed);
      } catch {
        return trimmed.slice(1, -1);
      }
    }

    return trimmed.slice(1, -1);
  }

  return trimmed;
}

function escapeShortcodeAttribute(value) {
  return String(value).replace(/\\/g, "\\\\").replace(/"/g, "\\\"");
}

function getFrontMatterValue(frontMatter, key) {
  const escapedKey = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const match = frontMatter.match(new RegExp(`^${escapedKey}:\\s*(.+?)\\s*$`, "m"));

  return match ? unquoteYamlString(match[1]) : "";
}

function hasFrontMatterKey(frontMatter, key) {
  const escapedKey = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`^${escapedKey}:`, "m").test(frontMatter);
}

function upsertFrontMatterScalar(frontMatter, key, value) {
  const escapedKey = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const line = `${key}: ${value}`;

  if (hasFrontMatterKey(frontMatter, key)) {
    return frontMatter.replace(new RegExp(`^${escapedKey}:.*$`, "m"), line);
  }

  return [frontMatter, line].filter(Boolean).join("\n");
}

function removeFrontMatterKeys(frontMatter, keys) {
  const lines = frontMatter.split(/\r?\n/);
  const output = [];

  for (const line of lines) {
    const key = line.match(/^([A-Za-z0-9_-]+):/)?.[1];

    if (key && keys.includes(key)) {
      continue;
    }

    output.push(line);
  }

  return output.join("\n").trim();
}

function toWebPath(cipherPath) {
  if (cipherPath.startsWith("static/")) {
    return `/${cipherPath.slice("static/".length)}`;
  }

  return cipherPath.startsWith("/") ? cipherPath : `/${cipherPath}`;
}

function titleFromEntry(entry, frontMatter) {
  return (
    getFrontMatterValue(frontMatter, "title") ||
    entry.title ||
    entry.plain
  );
}

function shouldIncludeInPrivateIndex(entry, frontMatter) {
  const value = getFrontMatterValue(frontMatter, "privateIndex");

  if (value) {
    return value !== "false";
  }

  return entry.privateIndex !== false && Boolean(entry.content);
}

function publicUrlFromEntry(entry, frontMatter) {
  if (entry.url) return entry.url;

  const slug = getFrontMatterValue(frontMatter, "slug");
  if (slug) return `/p/${slug}/`;

  return "";
}

function buildPublicArticle(entry, source) {
  const title = titleFromEntry(entry, source.frontMatter);
  const encryptedTitle = getFrontMatterValue(source.frontMatter, "encryptedTitle") || entry.encryptedTitle || "私密正文";
  const encryptedHint = getFrontMatterValue(source.frontMatter, "encryptedHint") || entry.encryptedHint || "";
  const intro =
    getFrontMatterValue(source.frontMatter, "privateIntro") ||
    entry.intro ||
    getFrontMatterValue(source.frontMatter, "summary") ||
    "这篇文章需要解锁后查看正文。";
  let publicFrontMatter = removeFrontMatterKeys(source.frontMatter, WORKFLOW_FRONT_MATTER_KEYS);

  if (!publicFrontMatter) {
    publicFrontMatter = `title: ${quoteYamlString(title)}`;
  }

  if (!hasFrontMatterKey(publicFrontMatter, "title")) {
    publicFrontMatter = upsertFrontMatterScalar(publicFrontMatter, "title", quoteYamlString(title));
  }

  if (!hasFrontMatterKey(publicFrontMatter, "draft")) {
    publicFrontMatter = upsertFrontMatterScalar(publicFrontMatter, "draft", "false");
  }

  if (!hasFrontMatterKey(publicFrontMatter, "comments")) {
    publicFrontMatter = upsertFrontMatterScalar(publicFrontMatter, "comments", "false");
  }

  if (!hasFrontMatterKey(publicFrontMatter, "toc")) {
    publicFrontMatter = upsertFrontMatterScalar(publicFrontMatter, "toc", "false");
  }

  const hint = encryptedHint
    ? ` hint="${escapeShortcodeAttribute(encryptedHint)}"`
    : "";
  const shortcode = `{{< encrypted src="${toWebPath(entry.cipher)}" title="${escapeShortcodeAttribute(encryptedTitle)}"${hint} >}}`;

  return [
    "---",
    publicFrontMatter,
    "---",
    "",
    GENERATED_NOTICE,
    "",
    intro,
    "",
    shortcode,
    ""
  ].join("\n");
}

function buildPrivateIndex(entries) {
  const links = entries
    .filter((entry) => entry.privateIndex && entry.url)
    .map((entry) => `- [${entry.title}](${entry.url})`)
    .join("\n");

  return [
    "---",
    'title: "私密文章"',
    'slug: "private"',
    "menu:",
    "    main:",
    "        name: 私密",
    "        weight: 5",
    "        params:",
    "            icon: archives",
    "comments: false",
    "toc: false",
    "---",
    "",
    GENERATED_NOTICE,
    "",
    '{{< encrypted-unlock title="解锁私密文章" >}}',
    "",
    "## 加密文章",
    "",
    links || "- 暂无加密文章",
    ""
  ].join("\n");
}

async function readPrivateSource(entry) {
  const content = await readFile(entry.plain, "utf8");
  return parseFrontMatter(content);
}

async function encryptEntry(entry) {
  const source = await readPrivateSource(entry);
  const title = titleFromEntry(entry, source.frontMatter);
  const payload = await encryptText(source.body.trimStart(), getPassword(), title);

  await writeJsonFile(entry.cipher, payload);
  console.log(`encrypted ${entry.plain} -> ${entry.cipher}`);

  if (entry.content) {
    await writeTextFile(entry.content, buildPublicArticle(entry, source));
    console.log(`generated ${entry.content}`);
  }

  return {
    title,
    url: publicUrlFromEntry(entry, source.frontMatter),
    privateIndex: shouldIncludeInPrivateIndex(entry, source.frontMatter)
  };
}

async function decryptEntry(entry) {
  const payload = await readJsonFile(entry.cipher);
  const plaintext = await decryptPayload(payload, getPassword());
  let frontMatter = "";

  try {
    frontMatter = parseFrontMatter(await readFile(entry.plain, "utf8")).frontMatter;
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }

  const title = entry.title || payload.title || entry.plain;

  if (!frontMatter) {
    frontMatter = `title: ${quoteYamlString(title)}`;
  }

  await writeTextFile(entry.plain, `---\n${frontMatter}\n---\n\n${plaintext}`);
  console.log(`decrypted ${entry.cipher} -> ${entry.plain}`);
}

async function main() {
  await loadEnv();

  const shouldEncrypt = argv.includes("--encrypt");
  const shouldDecrypt = argv.includes("--decrypt");
  const shouldSkipIndex = argv.includes("--skip-index");
  const manifestPath = getArg("--manifest") || "encrypted-manifest.json";
  const indexPath = getArg("--index") || "content/page/encrypted/index.md";

  if (shouldEncrypt === shouldDecrypt) {
    usage();
    exit(1);
  }

  const entries = await readJsonFile(manifestPath);

  if (!Array.isArray(entries)) {
    throw new Error(`${manifestPath} must be a JSON array.`);
  }

  for (const entry of entries) {
    if (!entry.plain || !entry.cipher) {
      throw new Error("Each manifest entry needs plain and cipher paths.");
    }
  }

  if (shouldEncrypt) {
    const generatedEntries = [];

    for (const entry of entries) {
      generatedEntries.push({
        ...entry,
        ...(await encryptEntry(entry))
      });
    }

    if (!shouldSkipIndex) {
      const indexEntries = generatedEntries.filter((entry) => entry.privateIndex);

      if (indexEntries.length > 0) {
        await writeTextFile(indexPath, buildPrivateIndex(indexEntries));
        console.log(`generated ${indexPath}`);
      }
    }

    return;
  }

  for (const entry of entries) {
    await decryptEntry(entry);
  }
}

main().catch((error) => {
  console.error(error.message || error);
  exit(1);
});
